Add dependency pyright and type check scripts

diff --git a/dev/hooks/pre-commit b/dev/hooks/pre-commit
--- a/dev/hooks/pre-commit
+++ b/dev/hooks/pre-commit
@@ -20,6 +20,15 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+echo "Checking types..."
+typecheck_output=$(pyright $py_dirs)
+
+if [ $? -ne 0 ]; then
+    echo "** ERROR: Type checking failed. Commit blocked. **"
+    echo "$typecheck_output"
+    exit 1
+fi
+
 echo "Running tests..."
 pytest
 
